# Generated by Django 2.2.9 on 2020-01-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reivew',
            new_name='review',
        ),
    ]
